# .streamlit/secrets.toml

[snowflake2]
user = "streamlit"
password = "Snowflake!234"
account = "demo175"
warehouse = "test_xs"
database = "citibike_ready"
schema = "public"

# .streamlit/secrets.toml

[snowflake]
user = "rblum"
password = "SnowRB01!"
account = "snowcat2.preprod5"
warehouse = "large_wh"
database = "demand"
schema = "public"
